// Predefined options for candidate profiles

// Top Universities (focused selection from our comprehensive list)
export const TOP_25_UNIVERSITIES = [
  "Princeton University",
  "Massachusetts Institute of Technology (MIT)",
  "Harvard University",
  "Stanford University",
  "Yale University",
  "University of Pennsylvania",
  "California Institute of Technology (Caltech)",
  "Duke University",
  "Brown University",
  "Northwestern University",
  "Dartmouth College",
  "Johns Hopkins University",
  "Columbia University",
  "Cornell University",
  "University of Chicago",
  "Vanderbilt University",
  "Rice University",
  "Washington University in St. Louis",
  "University of Notre Dame",
  "University of California, Berkeley",
  "University of California, Los Angeles (UCLA)",
  "Carnegie Mellon University",
  "Emory University",
  "Georgetown University",
  "University of Michigan, Ann Arbor"
];

export const UNIVERSITIES = [
  // District of Columbia
  "Georgetown University",
  "George Washington University",
  "American University",
  "Howard University",
  "Catholic University of America",
  "Gallaudet University",
  "University of the District of Columbia",
  
  // Maryland
  "Johns Hopkins University",
  "University of Maryland, College Park",
  "University of Maryland, Baltimore County (UMBC)",
  "Towson University",
  "Loyola University Maryland",
  "Salisbury University",
  "Morgan State University",
  "Bowie State University",
  "Frostburg State University",
  "Mount St. Mary's University",
  "University of Baltimore",
  "Goucher College",
  "Hood College",
  
  // Virginia (Northern + Major Universities)
  "University of Virginia",
  "Virginia Tech",
  "George Mason University",
  "William & Mary",
  "James Madison University",
  "Virginia Commonwealth University",
  "Old Dominion University",
  "Liberty University",
  "University of Mary Washington",
  "Christopher Newport University",
  "Radford University",
  "Washington and Lee University",
  "Virginia Military Institute",
  "Longwood University",
  "Regent University",
  
  // Top 50 National Universities (U.S. News 2025 Rankings)
  "Princeton University",
  "Massachusetts Institute of Technology (MIT)",
  "Harvard University",
  "Stanford University",
  "Yale University",
  "University of Pennsylvania",
  "California Institute of Technology (Caltech)",
  "Duke University",
  "Brown University",
  "Northwestern University",
  "Dartmouth College",
  "Columbia University",
  "Cornell University",
  "University of Chicago",
  "Vanderbilt University",
  "Rice University",
  "Washington University in St. Louis",
  "University of Notre Dame",
  "University of California, Berkeley",
  "University of California, Los Angeles (UCLA)",
  "Carnegie Mellon University",
  "Emory University",
  "University of Michigan, Ann Arbor",
  "University of Southern California (USC)",
  "University of North Carolina at Chapel Hill",
  "New York University (NYU)",
  "Wake Forest University",
  "Tufts University",
  "Boston College",
  "University of Florida",
  "University of California, San Diego (UCSD)",
  "University of Rochester",
  "University of Wisconsin–Madison",
  "University of Texas at Austin",
  "University of Illinois Urbana–Champaign",
  "Lehigh University",
  "University of Miami",
  "University of Washington",
  "College of William & Mary",
  "University of California, Davis",
  "University of Georgia",
  "Boston University",
  "Pennsylvania State University",
  "Purdue University",
  "Pepperdine University",
  "Rensselaer Polytechnic Institute (RPI)",
  "Ohio State University"
].sort();

export const MAJORS = [
  // Business & Economics
  "Business Administration",
  "Economics",
  "Finance",
  "Accounting",
  "Marketing",
  "Management",
  "International Business",
  "Entrepreneurship",
  "Supply Chain Management",
  "Human Resources",
  
  // Engineering
  "Computer Science",
  "Computer Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Biomedical Engineering",
  "Aerospace Engineering",
  "Industrial Engineering",
  "Environmental Engineering",
  
  // Sciences
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Statistics",
  "Psychology",
  "Neuroscience",
  "Biochemistry",
  "Environmental Science",
  "Geology",
  
  // Arts & Humanities
  "English",
  "History",
  "Philosophy",
  "Political Science",
  "Sociology",
  "Anthropology",
  "Art History",
  "Literature",
  "Religious Studies",
  "Classics",
  
  // Communications & Media
  "Communications",
  "Journalism",
  "Media Studies",
  "Public Relations",
  "Digital Media",
  "Film Studies",
  "Advertising",
  "Broadcasting",
  "Creative Writing",
  "Technical Writing",
  
  // Health & Medicine
  "Nursing",
  "Public Health",
  "Health Sciences",
  "Nutrition",
  "Kinesiology",
  "Pharmacy",
  "Pre-Medicine",
  "Dental Hygiene",
  "Occupational Therapy",
  "Physical Therapy",
  
  // Education
  "Elementary Education",
  "Secondary Education",
  "Special Education",
  "Early Childhood Education",
  "Educational Psychology",
  "Curriculum & Instruction",
  "Educational Leadership",
  "Adult Education",
  "Higher Education",
  "Educational Technology"
].sort();

export const MINORS = [
  // Business
  "Business",
  "Economics",
  "Finance",
  "Marketing",
  "Management",
  "Entrepreneurship",
  
  // Technology
  "Computer Science",
  "Information Technology",
  "Data Science",
  "Cybersecurity",
  "Web Development",
  "Mobile App Development",
  
  // Languages
  "Spanish",
  "French",
  "German",
  "Chinese",
  "Japanese",
  "Arabic",
  "Italian",
  "Portuguese",
  "Russian",
  "Korean",
  
  // Arts & Design
  "Graphic Design",
  "Digital Arts",
  "Photography",
  "Film",
  "Music",
  "Theater",
  "Dance",
  "Visual Arts",
  "Architecture",
  "Interior Design",
  
  // Sciences
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Statistics",
  "Psychology",
  "Neuroscience",
  "Environmental Science",
  "Astronomy",
  "Geology",
  
  // Social Sciences
  "Political Science",
  "Sociology",
  "Anthropology",
  "Geography",
  "International Relations",
  "Criminal Justice",
  "Social Work",
  "Women's Studies",
  "African American Studies",
  "Latin American Studies",
  
  // Professional
  "Leadership",
  "Public Speaking",
  "Project Management",
  "Conflict Resolution",
  "Negotiation",
  "Public Policy",
  "Law",
  "Pre-Law",
  "Pre-Medicine",
  "Pre-Dental"
].sort();

export const LOCATIONS = [
  // Major Cities
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  
  // Tech Hubs
  "San Francisco, CA",
  "Seattle, WA",
  "Austin, TX",
  "Denver, CO",
  "Boston, MA",
  "Washington, DC",
  "Atlanta, GA",
  "Miami, FL",
  "Nashville, TN",
  "Portland, OR",
  
  // Financial Centers
  "Charlotte, NC",
  "Minneapolis, MN",
  
  // Healthcare Centers
  "Baltimore, MD",
  "Cleveland, OH",
  "Rochester, MN",
  
  // Government & Policy
  "Arlington, VA",
  "Alexandria, VA",
  "Bethesda, MD",
  "Silver Spring, MD",
  "Rockville, MD",
  "Annapolis, MD",
  "Richmond, VA",
  "Harrisburg, PA",
  "Albany, NY"
];

export const SKILLS = [
  // Programming Languages
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Go",
  "Rust",
  "TypeScript",
  "Scala",
  "Perl",
  "R",
  "MATLAB",
  
  // Web Technologies
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Laravel",
  "Spring Boot",
  "ASP.NET",
  "WordPress",
  "Drupal",
  "Shopify",
  
  // Databases
  "SQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Oracle",
  "SQL Server",
  "SQLite",
  "Cassandra",
  "DynamoDB",
  "Firebase",
  "Elasticsearch",
  
  // Cloud & DevOps
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Git",
  "GitHub",
  "GitLab",
  "CI/CD",
  "Terraform",
  "Ansible",
  "Kubernetes",
  "Helm",
  
  // Data & Analytics
  "Data Analysis",
  "Machine Learning",
  "Deep Learning",
  "Data Visualization",
  "Tableau",
  "Power BI",
  "Excel",
  "SQL",
  "Python",
  "R",
  "SAS",
  "SPSS",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  
  // Design & Creative
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Figma",
  "Sketch",
  "Canva",
  "UI/UX Design",
  "Graphic Design",
  "Web Design",
  "Logo Design",
  "Branding",
  "Typography",
  "Color Theory",
  "Layout Design",
  
  // Business & Soft Skills
  "Project Management",
  "Leadership",
  "Communication",
  "Public Speaking",
  "Team Management",
  "Problem Solving",
  "Critical Thinking",
  "Time Management",
  "Customer Service",
  "Sales",
  "Marketing",
  "Business Development",
  "Strategic Planning",
  "Data Analysis",
  "Financial Analysis",
  "Analytical Thinking",
  "Attention to Detail",
  "Written Communication",
  "Presentation Skills",
  "Negotiation Skills",
  "Adaptability",
  "Client Relations",
  "Team Collaboration",
  "Cross-functional Collaboration",
  "Decision-making",
  "Negotiation",
  
  // Finance & Investment Banking
  "Financial Modeling",
  "Underwriting",
  "Valuation",
  "Due Diligence",
  "Risk Analysis",
  "Portfolio Management",
  "Forecasting",
  "Budgeting",
  "Capital Markets",
  "Asset Management",
  "Equity Research",
  "Investment Analysis",
  "Mergers & Acquisitions (M&A)",
  "Financial Reporting",
  "Discounted Cash Flow (DCF)",
  "Leveraged Buyouts (LBO)",
  "Return on Investment (ROI) Analysis",
  "Sensitivity Analysis",
  "Market Analysis",
  "Credit Analysis",
  "Private Equity",
  "Venture Capital",
  "Financial Planning & Analysis (FP&A)",
  "Bloomberg Terminal",
  "Excel Modeling",
  
  // Real Estate Finance
  "Real Estate Finance",
  "Property Valuation",
  "Site Selection",
  "Lease Analysis",
  "Deal Structuring",
  "Pro Forma Modeling",
  "Development Feasibility",
  "Construction Budgeting",
  "Due Diligence (Real Estate)",
  "Capital Stack Structuring",
  "Argus Enterprise",
  "Market Comps",
  "Zoning & Entitlements",
  "Land Acquisition",
  "Tenant Relations",
  "REIT Analysis",
  "Investment Memorandum Writing",
  "Appraisal",
  "Broker Relations",
  "Debt/Equity Financing",
  
  // Business Strategy & Operations
  "Market Research",
  "Competitive Analysis",
  "Operations Management",
  "Supply Chain",
  "Cost-benefit Analysis",
  "Pricing Strategy",
  "Financial Statement Analysis",
  "Business Intelligence",
  "Presentation Design",
  "KPI Tracking",
  "Economic Modeling",
  "Process Improvement",
  
  // Additional Software & Tools
  "Microsoft Excel (Advanced)",
  "Pivot Tables",
  "Excel Macros",
  "Salesforce",
  "QuickBooks",
  "Yardi",
  "Stata",
  "Google Sheets",
  "CoStar",
  "RealPage",
  "Adobe Acrobat",
  
];

export const WORK_PREFERENCES = [
  "Remote",
  "Hybrid",
  "On-site",
  "Flexible",
  "Travel Required",
  "International",
  "Local Only"
];

export const JOB_TYPES = [
  "Full-time",
  "Part-time",
  "Contract",
  "Internship",
  "Freelance",
  "Temporary",
  "Seasonal"
];

export const GRADUATION_YEARS = (() => {
  const years = [];
  
  // Generate years from 2020 to 2030
  for (let year = 2030; year >= 2020; year--) {
    years.push(year.toString());
  }
  
  return years;
})();

export const GPA_RANGES = [
  "3.9-4.0",
  "3.8-3.9",
  "3.7-3.8",
  "3.6-3.7",
  "3.5-3.6",
  "3.4-3.5",
  "3.3-3.4",
  "3.2-3.3",
  "3.1-3.2",
  "3.0-3.1",
  "2.9-3.0",
  "2.8-2.9",
  "2.7-2.8",
  "2.6-2.7",
  "2.5-2.6",
  "2.4-2.5",
  "2.3-2.4",
  "2.2-2.3",
  "2.1-2.2",
  "2.0-2.1",
  "Below 2.0",
  "Prefer not to say"
];

export const CERTIFICATIONS = {
  "Technology & Data": [
    "CompTIA A+",
    "CompTIA Network+",
    "CompTIA Security+",
    "AWS Certified Solutions Architect",
    "AWS Certified Cloud Practitioner",
    "Microsoft Certified: Azure Fundamentals",
    "Microsoft Certified: Azure Administrator Associate",
    "Google Cloud Professional Cloud Architect",
    "Cisco Certified Network Associate (CCNA)",
    "Certified Information Systems Security Professional (CISSP)",
    "Certified Ethical Hacker (CEH)",
    "Certified Information Security Manager (CISM)",
    "Python Institute PCEP / PCAP",
    "Tableau Desktop Specialist",
    "Power BI Data Analyst Associate",
    "Oracle Certified Professional (OCP)",
    "SQL Certification (Microsoft / Oracle / IBM)",
    "Google Data Analytics Professional Certificate",
    "IBM Data Science Professional Certificate"
  ],

  "Finance & Business": [
    "Certified Public Accountant (CPA)",
    "Chartered Financial Analyst (CFA)",
    "Certified Management Accountant (CMA)",
    "Financial Risk Manager (FRM)",
    "Series 7 License",
    "Series 63 License",
    "Certified Financial Planner (CFP)",
    "Bloomberg Market Concepts (BMC)",
    "QuickBooks Certification",
    "Excel Specialist / Microsoft Office Specialist (MOS)",
    "Project Management Professional (PMP)",
    "Certified ScrumMaster (CSM)",
    "Lean Six Sigma Green Belt",
    "Lean Six Sigma Black Belt"
  ],

  "Marketing & Communications": [
    "Google Analytics Certification",
    "Google Ads Certification",
    "HubSpot Inbound Marketing Certification",
    "HubSpot Content Marketing Certification",
    "Meta (Facebook) Blueprint Certification",
    "Hootsuite Social Media Marketing Certification",
    "SEMrush SEO Toolkit Certification",
    "Digital Marketing Institute (DMI) Professional Diploma",
    "Adobe Certified Professional (Photoshop / Illustrator)",
    "Canva Pro Design Certification"
  ],

  "Real Estate & Construction": [
    "Real Estate License",
    "Certified Commercial Investment Member (CCIM)",
    "LEED Green Associate",
    "LEED Accredited Professional (LEED AP)",
    "OSHA 10 / OSHA 30 Safety Certification",
    "Project Management Professional (PMP)",
    "Construction Management Certification (CMAA)",
    "Certified Property Manager (CPM)",
    "Building Performance Institute (BPI) Certification"
  ],

  "Healthcare & Life Sciences": [
    "Basic Life Support (BLS)",
    "Advanced Cardiac Life Support (ACLS)",
    "Registered Nurse (RN)",
    "Certified Nursing Assistant (CNA)",
    "Emergency Medical Technician (EMT)",
    "Pharmacy Technician Certification (CPhT)",
    "Certified Medical Assistant (CMA)",
    "Clinical Research Professional (CCRP)",
    "Health Information Management (RHIT / RHIA)"
  ],

  "Design & Creative": [
    "Adobe Certified Professional (Photoshop / Illustrator / After Effects)",
    "Autodesk Certified Professional (AutoCAD / Revit)",
    "UX Design Professional Certificate (Google)",
    "Figma Advanced Design Certification",
    "Canva Pro Design Certification"
  ],

  "General & Soft Skills": [
    "LinkedIn Learning Certificates (Various)",
    "Coursera Professional Certificates (Various)",
    "Udemy / edX Verified Certificates",
    "First Aid & CPR",
    "Customer Service Certification",
    "Leadership & Management Certificate",
    "Time Management Certification"
  ]
};

// Flattened list for dropdown usage
export const ALL_CERTIFICATIONS = Object.values(CERTIFICATIONS).flat();

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Chinese (Mandarin)",
  "Chinese (Cantonese)",
  "Japanese",
  "Arabic",
  "Italian",
  "Portuguese",
  "Russian",
  "Korean",
  "Hindi",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Polish",
  "Turkish",
  "Greek",
  "Hebrew",
  "Vietnamese",
  "Thai",
  "Indonesian",
  "Malay",
  "Tagalog (Filipino)",
  "Urdu",
  "Bengali",
  "Punjabi",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Swahili",
  "Czech",
  "Romanian",
  "Hungarian",
  "Bulgarian",
  "Croatian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Icelandic",
  "Irish",
  "Welsh",
  "Catalan",
  "Basque",
  "Farsi (Persian)",
  "Pashto",
  "Kurdish",
  "Amharic",
  "Yoruba",
  "Zulu",
  "Afrikaans",
  "Hausa",
  "Igbo",
  "Somali",
  "Berber",
  "Sign Language (ASL)",
  "Sign Language (BSL)",
  "Latin",
  "Sanskrit"
].sort();

export const CAREER_INTERESTS = [
  "Account Management",
  "Accounting & Auditing",
  "Advertising",
  "Aerospace",
  "Agriculture",
  "Airlines",
  "Architecture",
  "Artificial Intelligence & Machine Learning",
  "Arts & Culture",
  "Asset Management",
  "Automotive",
  "Biotechnology",
  "Blockchain & Cryptocurrency",
  "Brand Management",
  "Broadcasting",
  "Business Development",
  "Casino Operations",
  "Channel Sales",
  "Cloud Computing",
  "Clinical Research",
  "Commercial Banking",
  "Commercial Real Estate",
  "Community Development",
  "Construction Management",
  "Consumer Goods",
  "Content Creation",
  "Corporate Finance",
  "Cruise Lines",
  "Curriculum Development",
  "Cybersecurity",
  "Data Science & Analytics",
  "DevOps & Infrastructure",
  "Digital Marketing",
  "Diplomacy",
  "E-commerce",
  "Education Administration",
  "Educational Technology",
  "Energy & Utilities",
  "Entrepreneurship",
  "Environmental Conservation",
  "Event Planning",
  "Fashion & Apparel",
  "Field Sales",
  "Film & Television",
  "Financial Consulting",
  "Financial Planning",
  "Fintech",
  "Fishing",
  "Food & Beverage",
  "Forestry",
  "Game Development",
  "Government Relations",
  "Healthcare Administration",
  "Healthcare Policy",
  "Healthcare Technology",
  "Hotel Management",
  "HR Consulting",
  "Industrial Engineering",
  "Insurance",
  "Inside Sales",
  "Intelligence",
  "International Development",
  "International Relations",
  "Investment Banking",
  "Journalism",
  "Law Enforcement",
  "Legal Services",
  "Libraries",
  "Logistics",
  "Luxury Goods",
  "Management Consulting",
  "Manufacturing",
  "Marketing Consulting",
  "Medical Devices",
  "Medical Research",
  "Mental Health Services",
  "Merchandising",
  "Military",
  "Mining",
  "Mobile App Development",
  "Music & Audio",
  "Museums",
  "Non-Profit Management",
  "Oil & Gas",
  "Operations Consulting",
  "Operations Management",
  "Partnership Development",
  "Pharmaceuticals",
  "Policy Analysis",
  "Political Campaigning",
  "Politics",
  "Private Equity",
  "Product Management",
  "Property Management",
  "Procurement",
  "Public Administration",
  "Public Health",
  "Public Policy",
  "Public Relations",
  "Publishing",
  "Quality Assurance",
  "Real Estate Development",
  "Real Estate Finance",
  "Real Estate Investment",
  "Renewable Energy",
  "Research & Development",
  "Residential Real Estate",
  "Restaurant Management",
  "Retail Management",
  "Risk Management",
  "Sales Management",
  "Sales Operations",
  "Social Media Marketing",
  "Social Work",
  "Software Engineering",
  "Sports & Entertainment",
  "Startups",
  "Strategy Consulting",
  "Supply Chain Management",
  "Tax Services",
  "Technology Consulting",
  "Telecommunications",
  "Trading & Markets",
  "Transportation",
  "Travel & Tourism",
  "UX/UI Design",
  "Urban Planning",
  "Venture Capital"
].sort();
